services:
  master-node:
    image: mongo:6.0
    command: --config /etc/mongo/mongod.conf
    hostname: ${MONGO_REPLICA_SET_HOST}
    env_file:
      - .env
    ports:
      - ${EXPOSED_IP}:${EXPOSED_PORT:-27017}:27017
    volumes:
      - ./data:/data/db
      - ./log:/var/log/mongodb
      - ./config:/etc/mongo